"use client";
import { useState } from "react";
import type { CmsDomain, CmsInvitation, CmsMember, CmsRole, CmsSite } from "../../db/cms";
import { AsyncForm, BusinessField as Field, BusinessTable, RecordPage, useBusinessView } from "../components/backoffice";
import { workspaceRequest } from "../merchant/workspace-api";

function cmsWrite<T>(resource:string, fields:Record<string,unknown>, method="POST") {return workspaceRequest<T>(`/api/cms/${resource}`,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(fields)});}
const roles:Record<CmsRole,string>={owner:"站点管理负责人",editor:"站点内容协作者",viewer:"仅查看"};

export function PlatformSites({sites,canCreate,onCreated,onSelect}:{sites:CmsSite[];canCreate:boolean;onCreated:(site:CmsSite)=>void;onSelect:(site:CmsSite)=>void}){
  const {view,open}=useBusinessView("platform:sites");
  if(view==="new")return <RecordPage title="从模板创建站点" description="适用于平台代建。申请人的站点请从“商户申请”审核通过后创建，自动关联负责人。" onBack={()=>open()}><SiteWizard sites={sites} disabled={!canCreate} onCreated={site=>{onCreated(site);open();}}/></RecordPage>;
  return <BusinessTable title="商户站点" rows={sites} rowKey={s=>s.id} searchText={s=>`${s.name} ${s.slug} ${s.domain}`} status={s=>s.status} columns={[{label:"站点名称",render:s=><><strong>{s.name}</strong><small>{s.slug}</small></>},{label:"域名",render:s=>s.domain||"尚未绑定"},{label:"状态",render:s=>s.status},{label:"最后更新",render:s=>new Date(s.updatedAt).toLocaleString()}]} onOpen={onSelect} openLabel="交付详情" actions={<button type="button" className="button button-dark" disabled={!canCreate} onClick={()=>open("new")}>＋ 创建商户站点</button>}/>;
}

function SiteWizard({sites,disabled,onCreated}:{sites:CmsSite[];disabled:boolean;onCreated:(site:CmsSite)=>void}){
  const [step,setStep]=useState(1);const [draft,setDraft]=useState({name:"",slug:"",templateSiteId:sites[0]?.id||"default"});
  return <div className="bo-card"><div className="bo-info">{step} / 3 · {step===1?"填写站点资料":step===2?"选择复制来源":"确认创建内容"}</div><AsyncForm key={step} disabled={disabled} label={step<3?"下一步":"确认创建站点"} onSave={async form=>{
    if(step===1){const name=String(form.get("name")).trim(),slug=String(form.get("slug")).trim();if(sites.some(s=>s.slug===slug))throw new Error("站点标识已存在，请换一个。");setDraft(current=>({...current,name,slug}));setStep(2);return;}
    if(step===2){setDraft(current=>({...current,templateSiteId:String(form.get("templateSiteId"))}));setStep(3);return;}
    const result=await cmsWrite<{site:CmsSite}>("sites",draft);onCreated(result.site);
  }}>{step===1?<div className="bo-form-grid"><Field label="商户 / 品牌名称 *"><input name="name" defaultValue={draft.name} required maxLength={100}/></Field><Field label="站点访问标识 *"><input name="slug" defaultValue={draft.slug} required pattern="[a-z0-9]+(-[a-z0-9]+)*"/></Field></div>:step===2?<><Field label="复制来源站点 *"><select name="templateSiteId" defaultValue={draft.templateSiteId}>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><p className="bo-info">复制当前系统支持的品牌、首页、商品和媒体资料。新站仍需配置负责人、支付、域名并通过上线检查；不会自动迁入来源站点的订单。</p></>:<dl className="bo-facts"><div><dt>站点名称</dt><dd>{draft.name}</dd></div><div><dt>站点标识</dt><dd>{draft.slug}</dd></div><div><dt>模板来源</dt><dd>{sites.find(s=>s.id===draft.templateSiteId)?.name}</dd></div><div><dt>后续事项</dt><dd>负责人、品牌检查、支付邮件、域名和发布。</dd></div></dl>}</AsyncForm>{step>1&&<button type="button" className="text-button" onClick={()=>setStep(step-1)}>返回上一步</button>}</div>;
}

export function PlatformDomains({siteId,domains,canWrite,onChange}:{siteId:string;domains:CmsDomain[];canWrite:boolean;onChange:(domains:CmsDomain[])=>void}){
  const {view,record,open}=useBusinessView(siteId+":domains");const domain=domains.find(d=>d.id===record);
  if(view)return <RecordPage title={view==="new"?"绑定自定义域名":"域名接入详情"} onBack={()=>open()}>{view==="new"?<div className="bo-card"><AsyncForm disabled={!canWrite} label="提交域名绑定" onSave={async form=>{const hostname=String(form.get("hostname")).trim().toLowerCase();if(!/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,63}$/.test(hostname))throw new Error("请输入域名，不包含 https://、端口或页面路径。");const result=await cmsWrite<{domain:CmsDomain}>("domains",{siteId,hostname});onChange([...domains.filter(d=>d.id!==result.domain.id),result.domain]);open("detail",result.domain.id);}}><Field label="域名 *"><input name="hostname" required placeholder="shop.example.com"/></Field><p className="bo-info">此操作提交接入记录，不代表 DNS 和证书已经生效。</p></AsyncForm></div>:!domain?<div className="bo-empty">域名记录不存在。</div>:<div className="bo-card"><h3>{domain.hostname}</h3><dl className="bo-facts">{[["接入状态",domain.status],["DNS 目标",domain.dnsTarget||"等待平台提供接入目标"],["证书状态",domain.sslStatus||"待检查"],["最近检查",domain.lastCheckedAt||"尚未检查"],["问题说明",domain.lastError||"暂无异常记录"]].map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl><AsyncForm disabled={!canWrite} label="重新检查解析与证书" onSave={async()=>{await cmsWrite("domains/check",{siteId,domainId:domain.id});const result=await workspaceRequest<{domains:CmsDomain[]}>(`/api/cms/domains?siteId=${encodeURIComponent(siteId)}`);onChange(result.domains);}}><p className="bo-info">请先在域名服务商添加正式部署平台提供的记录，再发起检查。不会用手动选“成功”替代真实验证。</p></AsyncForm></div>}</RecordPage>;
  return <BusinessTable title="域名管理" rows={domains} rowKey={d=>d.id} searchText={d=>d.hostname} status={d=>d.status} columns={[{label:"域名",render:d=>d.hostname},{label:"状态",render:d=>d.status},{label:"证书",render:d=>d.sslStatus||"待检查"},{label:"最近检查",render:d=>d.lastCheckedAt||"尚未检查"}]} onOpen={d=>open("detail",d.id)} actions={<button type="button" className="button button-dark" disabled={!canWrite} onClick={()=>open("new")}>＋ 绑定域名</button>}/>;
}

export function PlatformMembers({siteId,members,invitations,canWrite,onRefresh}:{siteId:string;members:CmsMember[];invitations:CmsInvitation[];canWrite:boolean;onRefresh:()=>Promise<void>}){
  const {view,record,open}=useBusinessView(siteId+":members");const member=members.find(m=>m.userId===record);const [inviteUrl,setInviteUrl]=useState("");
  if(view)return <RecordPage title={view==="new"?"邀请站点协作者":"管理协作者权限"} onBack={()=>open()} description="权限范围限于当前所选站点。商家员工请在商家后台管理。"><div className="bo-card">{view!=="new"&&!member?<p>成员不存在。</p>:<AsyncForm disabled={!canWrite||member?.role==="owner"} label={member?"保存权限":"创建邀请"} onSave={async form=>{const result=await cmsWrite<{invitation?:CmsInvitation}>("members",{siteId,...(member?{userId:member.userId}:{}),email:form.get("email"),role:form.get("role")},member?"PATCH":"POST");if(result.invitation?.inviteUrl)setInviteUrl(new URL(result.invitation.inviteUrl,window.location.origin).href);await onRefresh();if(member)open();}}><Field label="邮箱 *"><input name="email" type="email" required defaultValue={member?.email} readOnly={!!member}/></Field><Field label="站点权限"><select name="role" defaultValue={member?.role||"viewer"}><option value="editor">内容协作者</option><option value="viewer">仅查看</option>{member?.role==="owner"&&<option value="owner">站点负责人（受保护）</option>}</select></Field><p className="bo-info">邀请创建后显示链接；是否接受以邀请记录为准，不冒充邮件已经送达。</p></AsyncForm>}{member&&member.role!=="owner"&&canWrite&&<AsyncForm label="移除访问权限" onSave={async()=>{if(!window.confirm("确认移除 "+member.email+" 的当前站点权限？"))return;await workspaceRequest("/api/cms/members?siteId="+encodeURIComponent(siteId)+"&userId="+encodeURIComponent(member.userId),{method:"DELETE"});await onRefresh();open();}}><p>只影响当前站点，不删除用户账号。</p></AsyncForm>}{inviteUrl&&<Field label="邀请链接（复制给协作者）"><input value={inviteUrl} readOnly onFocus={event=>event.target.select()}/></Field>}</div></RecordPage>;
  return <><BusinessTable title="站点协作者" rows={members} rowKey={m=>m.userId} searchText={m=>m.email} columns={[{label:"邮箱",render:m=>m.email},{label:"权限",render:m=>roles[m.role]},{label:"加入时间",render:m=>new Date(m.createdAt).toLocaleString()}]} onOpen={m=>open("edit",m.userId)} openLabel="管理权限" actions={<button type="button" className="button button-dark" disabled={!canWrite} onClick={()=>{setInviteUrl("");open("new");}}>＋ 邀请协作者</button>}/><BusinessTable title="邀请记录" rows={invitations} rowKey={i=>i.id} searchText={i=>i.email} status={i=>i.status} columns={[{label:"邮箱",render:i=>i.email},{label:"权限",render:i=>roles[i.role]},{label:"状态",render:i=>i.status},{label:"过期时间",render:i=>new Date(i.expiresAt).toLocaleString()},{label:"操作",render:i=>i.status==="pending"?<AsyncForm disabled={!canWrite} label="撤销邀请" onSave={async()=>{if(!window.confirm("撤销此协作者邀请？"))return;await workspaceRequest("/api/cms/members?siteId="+encodeURIComponent(siteId)+"&invitationId="+encodeURIComponent(i.id),{method:"DELETE"});await onRefresh();}}><span className="sr-only">{i.email}</span></AsyncForm>:"—"}]}/></>;
}
