"use client";

import { useEffect, useMemo, useState } from "react";
import { AsyncForm, BusinessField as Field, BusinessTable, RecordPage, useBusinessView } from "../components/backoffice";
import { workspaceRequest } from "../merchant/workspace-api";

type Plan = { id: string; name: string; currency: string; monthlyFee: number; annualFee: number };
type Invoice = { id: string; invoiceNumber: string; kind: string; amount: number; currency: string; status: string; dueAt: string; paidAt: string | null; retryCount: number; failureReason: string | null };
type Merchant = {
  application: { id: string; brandName: string; companyName: string; email: string; status: string; assignedSiteId: string | null; templateSiteId: string; ownerInviteStatus?: string; createdAt: string };
  commercial: { plan: Plan | null; subscription: { status: string; billingInterval: string; recurringFee: number; currency: string; trialEndsAt: string | null; nextBillingAt: string | null; graceUntil: string | null } | null; invoices: Invoice[] };
  delivery: { siteId: string | null; siteStatus: string | null; domain: string | null; domainStatus: string | null; publishedProducts: number; credentialProviders: number; isolatedCredentials: boolean; publishedVersions: number; latestReleaseAt: string | null };
  operations: { readinessScore: number; readinessDone: number; readinessTotal: number; healthStatus: string; openTickets: number; failedNotifications: number; failedPayments: number; unresolvedEvents: number; nextAction: string };
};
type Snapshot = { generatedAt: string; metrics: Record<string, number>; merchants: Merchant[]; revenueByMonth: Array<{ month: string; collected: number; invoices: number }>; applicationsByMonth: Array<{ month: string; applications: number; approved: number }> };

const applicationLabels: Record<string,string> = {draft:"未提交",submitted:"待审核",reviewing:"审核中",needs_info:"待补资料",approved:"已通过",commercial_pending:"待确认套餐",site_creating:"创建中",onboarding_failed:"交付失败",rejected:"已拒绝",site_created:"站点已创建",live:"已上线",suspended:"已暂停"};
const subscriptionLabels: Record<string,string> = {draft:"未选套餐",pending_signature:"待签约",trialing:"试用中",active:"正常续费",past_due:"已欠费",cancelled:"已取消",expired:"已到期"};
const money=(amount:number,currency="USD")=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:currency.toUpperCase()}).format(amount||0);
const date=(value:string|null|undefined)=>value?new Date(value).toLocaleString("zh-CN"):"—";

export function V60PlatformPanel({ reportOnly = false }: { reportOnly?: boolean }) {
  const { view, record, open } = useBusinessView(reportOnly ? "platform:v60:reports" : "platform:v60:merchants");
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null);
  const [plans,setPlans]=useState<Plan[]>([]);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [notice,setNotice]=useState("");
  const [revision,setRevision]=useState(0);
  useEffect(()=>{const abort=new AbortController();async function load(){setLoading(true);setError("");try{const [data,planData]=await Promise.all([workspaceRequest<Snapshot>("/api/platform/operations",{signal:abort.signal}),workspaceRequest<{plans:Plan[]}>("/api/platform/plans",{signal:abort.signal})]);if(!abort.signal.aborted){setSnapshot(data);setPlans(planData.plans);}}catch(cause){if(!abort.signal.aborted)setError(cause instanceof Error?cause.message:"平台经营数据加载失败");}finally{if(!abort.signal.aborted)setLoading(false);}}void load();return()=>abort.abort();},[revision]);
  const selected=useMemo(()=>snapshot?.merchants.find(item=>item.application.id===record)||null,[snapshot,record]);
  async function action(payload:Record<string,unknown>,confirmation?:string){if(confirmation&&!window.confirm(confirmation))return;await workspaceRequest("/api/platform/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});setNotice("操作已完成并写入记录。");setRevision(value=>value+1);}
  async function createSite(merchant:Merchant){if(!window.confirm("按申请选择的模板复制品牌、首页、商品和媒体，并创建隔离的客户站点？"))return;await workspaceRequest("/api/platform/applications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:merchant.application.id,status:"site_created",createSite:true})});setNotice("客户站点已创建，负责人邀请和交付记录已生成。");setRevision(value=>value+1);}
  if(loading)return <div className="bo-card" role="status">正在汇总商户、套餐、交付与经营数据…</div>;
  if(error)return <div className="bo-error" role="alert">{error}<button type="button" onClick={()=>setRevision(v=>v+1)}>重新加载</button></div>;
  if(!snapshot)return null;
  if(reportOnly)return <PlatformReports snapshot={snapshot}/>;
  if(view&&selected){
    const a=selected.application,s=selected.commercial.subscription;
    return <RecordPage title={a.brandName+" · 商户全流程"} description={a.id+" · 当前下一步："+selected.operations.nextAction} onBack={()=>open()}>
      {notice&&<div className="bo-info" role="status">{notice}</div>}
      <div className="bo-metrics">{[["入驻状态",applicationLabels[a.status]||a.status],["套餐状态",subscriptionLabels[s?.status||"draft"]||s?.status],["上线准备",selected.operations.readinessScore+"%"],["经营健康",selected.operations.healthStatus==="healthy"?"正常":selected.operations.healthStatus==="critical"?"需立即处理":"待完善"]].map(([label,value])=><div className="bo-metric" key={label}>{label}<strong>{value}</strong></div>)}</div>
      <div className="bo-record-layout">
        <section className="bo-card"><h3>套餐、试用与续费</h3><dl className="bo-facts"><div><dt>当前套餐</dt><dd>{selected.commercial.plan?.name||"尚未选择"}</dd></div><div><dt>计费周期</dt><dd>{s?.billingInterval==="annual"?"年付":"月付"}</dd></div><div><dt>续费金额</dt><dd>{s?money(s.recurringFee,s.currency):"—"}</dd></div><div><dt>试用结束</dt><dd>{date(s?.trialEndsAt)}</dd></div><div><dt>下次计费</dt><dd>{date(s?.nextBillingAt)}</dd></div><div><dt>欠费宽限期</dt><dd>{date(s?.graceUntil)}</dd></div></dl>
          {!s&&<AsyncForm label="保存套餐" onSave={async form=>{await workspaceRequest("/api/platform/commercial",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"select_plan",applicationId:a.id,planId:form.get("planId"),billingInterval:form.get("billingInterval")})});setRevision(v=>v+1);}}><Field label="套餐"><select name="planId" required>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.name} · {money(plan.monthlyFee,plan.currency)}/月</option>)}</select></Field><Field label="付费周期"><select name="billingInterval"><option value="monthly">按月</option><option value="annual">按年</option></select></Field></AsyncForm>}
          {s&&<div className="bo-actions"><button className="button button-outline" onClick={()=>void action({action:"reconcile",applicationId:a.id})}>检查到期状态</button>{["pending_signature","draft","expired","cancelled"].includes(s.status)&&<button className="button button-dark" onClick={()=>void action({action:"start_trial",applicationId:a.id,trialDays:14},"为该商户启动 14 天试用？")}>启动 14 天试用</button>}{["active","past_due"].includes(s.status)&&<button className="button button-outline" onClick={()=>void action({action:"create_renewal",applicationId:a.id})}>生成续费账单</button>}{["past_due","expired","cancelled"].includes(s.status)&&<button className="button button-dark" onClick={()=>void action({action:"reactivate",applicationId:a.id},"确认恢复套餐并开始新的计费周期？")}>恢复服务</button>}{!["cancelled","expired"].includes(s.status)&&<button className="text-button danger" onClick={()=>void action({action:"cancel",applicationId:a.id},"取消套餐会暂停已上线商户的服务，确认继续？")}>取消套餐</button>}</div>}
        </section>
        <section className="bo-card"><h3>客户交付与数据隔离</h3><dl className="bo-facts"><div><dt>模板</dt><dd>{a.templateSiteId}</dd></div><div><dt>客户站点</dt><dd>{selected.delivery.siteId||"尚未创建"}</dd></div><div><dt>负责人账号</dt><dd>{a.ownerInviteStatus==="accepted"?"已激活":"待激活"}</dd></div><div><dt>独立商品数据</dt><dd>{selected.delivery.siteId?selected.delivery.publishedProducts+" 个已发布商品":"待创建站点"}</dd></div><div><dt>独立密钥</dt><dd>{selected.delivery.isolatedCredentials?"PayPal 与 Resend 已按站点隔离":selected.delivery.credentialProviders+"/2 项已就绪"}</dd></div><div><dt>密钥安全</dt><dd>仅展示状态，不返回密钥明文</dd></div></dl><div className="bo-actions">{!selected.delivery.siteId&&["approved","commercial_pending","onboarding_failed","site_creating"].includes(a.status)&&<button className="button button-dark" onClick={()=>void createSite(selected)}>一键复制模板并建站</button>}<a className="button button-outline" href={"/admin?tab=merchants&view=detail&record="+encodeURIComponent(a.id)}>审核与交付详情</a>{selected.delivery.siteId&&<a className="button button-outline" href={"/admin?tab=v23&siteId="+encodeURIComponent(selected.delivery.siteId)}>配置独立密钥</a>}</div></section>
      </div>
      <div className="bo-record-layout">
        <section className="bo-card"><h3>域名、上线与版本</h3><dl className="bo-facts"><div><dt>申请域名</dt><dd>{selected.delivery.domain||"尚未提交"}</dd></div><div><dt>接入状态</dt><dd>{selected.delivery.domainStatus||"待接入"}</dd></div><div><dt>已发布版本</dt><dd>{selected.delivery.publishedVersions}</dd></div><div><dt>最近发布</dt><dd>{date(selected.delivery.latestReleaseAt)}</dd></div><div><dt>上线进度</dt><dd>{selected.operations.readinessDone}/{selected.operations.readinessTotal} 项完成</dd></div></dl>{selected.delivery.siteId&&<div className="bo-actions"><a className="button button-outline" href={"/admin?tab=domains&siteId="+encodeURIComponent(selected.delivery.siteId)}>域名接入</a><a className="button button-outline" href={"/admin?tab=v24&siteId="+encodeURIComponent(selected.delivery.siteId)}>上线检查</a><a className="button button-dark" href={"/admin?tab=release&siteId="+encodeURIComponent(selected.delivery.siteId)}>发布与回滚</a><a className="button button-outline" href={"/admin?tab=activity&siteId="+encodeURIComponent(selected.delivery.siteId)}>操作记录</a></div>}</section>
        <section className="bo-card"><h3>健康度与异常处置</h3><dl className="bo-facts"><div><dt>未处理工单</dt><dd>{selected.operations.openTickets}</dd></div><div><dt>支付失败</dt><dd>{selected.operations.failedPayments}</dd></div><div><dt>邮件失败</dt><dd>{selected.operations.failedNotifications}</dd></div><div><dt>运行异常</dt><dd>{selected.operations.unresolvedEvents}</dd></div><div><dt>建议动作</dt><dd>{selected.operations.nextAction}</dd></div></dl><div className="bo-actions"><a className="button button-outline" href={"/admin?tab=merchants&view=detail&record="+encodeURIComponent(a.id)}>处理工单与通知</a>{selected.delivery.siteId&&<a className="button button-outline" href={"/admin?tab=v21&siteId="+encodeURIComponent(selected.delivery.siteId)}>查看支付与运行异常</a>}</div></section>
      </div>
      <BusinessTable title="平台账单与收款记录" rows={selected.commercial.invoices} rowKey={invoice=>invoice.id} searchText={invoice=>invoice.invoiceNumber+" "+invoice.status} status={invoice=>invoice.status} columns={[{label:"账单号",render:invoice=>invoice.invoiceNumber},{label:"类型",render:invoice=>invoice.kind},{label:"金额",render:invoice=>money(invoice.amount,invoice.currency)},{label:"到期时间",render:invoice=>date(invoice.dueAt)},{label:"重试",render:invoice=>invoice.retryCount},{label:"失败原因",render:invoice=>invoice.failureReason||"—"},{label:"操作",render:invoice=>["open","failed"].includes(invoice.status)?<div className="bo-actions"><button className="text-button" onClick={()=>void action({action:"payment_paid",invoiceId:invoice.id,providerReference:"manual-"+Date.now()},"确认已收到该笔平台服务费？")}>标记收款</button><button className="text-button danger" onClick={()=>void action({action:"payment_failed",invoiceId:invoice.id,failureReason:"平台人工记录：本次扣款失败"})}>记录失败</button></div>:"—"}]}/>
    </RecordPage>;
  }
  return <><div className="bo-metrics">{[["待审核申请",snapshot.metrics.pendingReviews],["已创建商户",snapshot.metrics.merchants],["试用中",snapshot.metrics.activeTrials],["欠费商户",snapshot.metrics.pastDueSubscriptions],["待处理工单",snapshot.metrics.openTickets]].map(([label,value])=><div className="bo-metric" key={label}>{label}<strong>{value}</strong></div>)}</div><BusinessTable title="商户全生命周期" rows={snapshot.merchants} rowKey={item=>item.application.id} searchText={item=>[item.application.brandName,item.application.companyName,item.application.email,item.delivery.domain].join(" ")} status={item=>item.operations.healthStatus} columns={[{label:"商户",render:item=><><strong>{item.application.brandName}</strong><small>{item.application.email}</small></>},{label:"入驻",render:item=>applicationLabels[item.application.status]||item.application.status},{label:"套餐",render:item=>subscriptionLabels[item.commercial.subscription?.status||"draft"]},{label:"交付进度",render:item=>item.operations.readinessScore+"%"},{label:"站点 / 域名",render:item=><>{item.delivery.siteId||"待创建"}<small>{item.delivery.domain||"待绑定域名"}</small></>},{label:"当前下一步",render:item=>item.operations.nextAction}]} onOpen={item=>{setNotice("");open("detail",item.application.id);}} openLabel="管理商户" actions={<button className="button button-outline" onClick={()=>setRevision(v=>v+1)}>刷新数据</button>}/></>;
}

function PlatformReports({snapshot}:{snapshot:Snapshot}){
  const metrics=snapshot.metrics;
  return <><div className="bo-metrics">{[["预计月经常收入",money(metrics.monthlyRecurringRevenue)],["累计已收",money(metrics.collectedRevenue)],["待收与失败",money(metrics.outstandingRevenue)],["正常续费商户",metrics.activeSubscriptions],["支付异常",metrics.failedPayments]].map(([label,value])=><div className="bo-metric" key={label}>{label}<strong>{value}</strong></div>)}</div><div className="bo-record-layout"><BusinessTable title="月度收入" rows={snapshot.revenueByMonth} rowKey={row=>row.month} searchText={row=>row.month} columns={[{label:"月份",render:row=>row.month},{label:"已收服务费",render:row=>money(row.collected)},{label:"已付账单",render:row=>row.invoices}]}/><BusinessTable title="入驻转化" rows={snapshot.applicationsByMonth} rowKey={row=>row.month} searchText={row=>row.month} columns={[{label:"月份",render:row=>row.month},{label:"申请数",render:row=>row.applications},{label:"通过数",render:row=>row.approved},{label:"通过率",render:row=>row.applications?Math.round(row.approved/row.applications*100)+"%":"0%"}]}/></div><p className="bo-info">报表仅汇总平台套餐账单，不混入各商户商城的商品销售额；两类资金归属保持分离。</p></>;
}
