"use client";

import { FormEvent, useEffect, useState } from "react";

type Review = { id: string; rating: number; title: string | null; body: string; createdAt: string };
export function ProductReviews({ productId }: { productId: string }) {
  const [reviews, setReviews] = useState<Review[]>([]); const [form, setForm] = useState({ email: "", orderNumber: "", rating: "5", title: "", body: "" }); const [message, setMessage] = useState("");
  useEffect(() => { void fetch(`/api/reviews?productId=${encodeURIComponent(productId)}`).then((response) => response.json()).then((payload: { reviews?: Review[] }) => setReviews(payload.reviews || [])).catch(() => undefined); }, [productId]);
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch("/api/reviews", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ productId, ...form, rating: Number(form.rating) }) }); const payload = await response.json().catch(() => ({})) as { error?: string }; setMessage(response.ok ? "Thanks. Your review is waiting for approval." : payload.error || "Review could not be submitted."); if (response.ok) setForm({ email: "", orderNumber: "", rating: "5", title: "", body: "" }); }
  return <section className="reviews-section"><div className="section-heading"><p className="eyebrow">Field notes</p><h2>Customer reviews.</h2></div><div className="review-list">{reviews.map((review) => <article key={review.id}><strong>{"★".repeat(review.rating)}</strong><h3>{review.title || "Verified field note"}</h3><p>{review.body}</p></article>)}{!reviews.length && <p className="v6-muted">No approved reviews yet. Be the first to share a field note.</p>}</div><form className="review-form" onSubmit={submit}><p className="eyebrow">Leave a review</p><div className="form-two"><label><span>Email</span><input type="email" required value={form.email} onChange={(event) => setForm((current) => ({ ...current, email: event.target.value }))} /></label><label><span>Order number</span><input required value={form.orderNumber} onChange={(event) => setForm((current) => ({ ...current, orderNumber: event.target.value }))} /></label></div><div className="form-two"><label><span>Rating</span><select value={form.rating} onChange={(event) => setForm((current) => ({ ...current, rating: event.target.value }))}><option value="5">5 / 5</option><option value="4">4 / 5</option><option value="3">3 / 5</option><option value="2">2 / 5</option><option value="1">1 / 5</option></select></label><label><span>Title</span><input value={form.title} onChange={(event) => setForm((current) => ({ ...current, title: event.target.value }))} /></label></div><label><span>Review</span><textarea required value={form.body} onChange={(event) => setForm((current) => ({ ...current, body: event.target.value }))} /></label>{message && <p className="form-help" role="status">{message}</p>}<button className="button button-outline">Submit review</button></form></section>;
}
