"use client";

import Link from "next/link";
import { useSiteRuntime } from "../components/site-runtime";

export default function AboutPage() {
  const { config } = useSiteRuntime();
  return <div className="about-page"><section className="about-hero container section-pad"><p className="eyebrow">{config.content.about.label}</p><h1>{config.content.about.titleLead}<br /><em>{config.content.about.titleAccent}</em></h1><p className="about-lead">{config.content.about.lead}</p></section><section className="about-image"><img src={config.assets.aboutHero} alt="Tent beside a calm mountain lake" /></section><section className="about-copy container section-pad"><div className="section-kicker"><span>02</span><span>Our point of view</span></div><div className="about-copy-grid"><h2>Useful can<br /><em>still be beautiful.</em></h2><div><p className="lead">We believe the things you carry should earn their place. That means fewer features, better materials, and designs that get more comfortable with time.</p><p>{config.brand.name} began around a kitchen table after one too many trips with gear that was too loud, too complicated, or simply not made to last. Today, we work with a small group of makers who share our patient approach.</p><p>Every piece is made to move through real life: early flights, muddy trailheads, borrowed cabins, and the quiet commute home.</p><Link href="/shop" className="text-link">See the collection -&gt;</Link></div></div></section><section className="values-section"><div className="container"><p className="eyebrow">{config.content.about.valuesLabel}</p><div className="values-grid"><div><span>01</span><h3>Less, better</h3><p>We edit hard so you can pack light and keep the pieces that matter.</p></div><div><span>02</span><h3>Made to move</h3><p>Real utility, intuitive details, and materials that don&apos;t need babysitting.</p></div><div><span>03</span><h3>Leave a trace</h3><p>We are working toward lower-impact materials and less waste at every step.</p></div></div></div></section></div>;
}
