"use client";

import { useState } from "react";
import type { CmsAsset } from "../../db/cms";
import type { PortalProduct, InventoryRow } from "../client/client-portal";
import { AsyncForm, BusinessField as Field, BusinessTable, RecordPage, useBusinessView } from "../components/backoffice";
import { formatMoney } from "../lib/format-money";
import { variantOptionValues } from "../data/products";
import { workspaceRequest, merchantWrite, productStatus } from "./workspace-api";

export function MerchantCatalog({ siteId, products, assets, canWrite, onProducts, onExport, initialFilter = "" }: {initialFilter?:string; siteId: string; products: PortalProduct[]; assets: CmsAsset[]; canWrite: boolean; onProducts: (products: PortalProduct[]) => void; onExport: () => void}) {
  const {view, record, open} = useBusinessView(siteId + ":products");
  const selected = products.find(product => product.id === record);
  if(view === "new" || view === "edit") return <RecordPage title={view === "new" ? "新增商品" : "编辑商品"} onBack={() => open()} description="保存进入当前店铺草稿，发布审核通过后才更新商城。" aside={<div className="bo-info">商品资料与实时库存分开维护。已有商品的补货、盘点请到“库存管理”，这里的库存只用于新增商品初始化。</div>}>
    {view === "edit" && !selected ? <div className="bo-empty">此商品不存在，请返回列表刷新。</div> : <ProductForm siteId={siteId} key={selected?.id || "new"} product={selected} assets={assets} disabled={!canWrite} save={async fields => {
      const result = await merchantWrite<{product: PortalProduct}>(siteId, "products", selected ? "PATCH" : "POST", {...fields, ...(selected ? {productId:selected.id} : {})});
      onProducts(selected ? products.map(product => product.id === selected.id ? result.product : product) : [...products,result.product]); open();
    }} />}
    {selected&&canWrite&&<details className="bo-card"><summary>删除此商品</summary><AsyncForm label="确认删除商品" onSave={async()=>{if(!window.confirm("删除会从当前目录及已发布记录移除此商品，不只是保存草稿；已锁定库存的商品不能删除。确认继续？"))return;await merchantWrite(siteId,"products","DELETE",{productId:selected.id});onProducts(products.filter(p=>p.id!==selected.id));open();}}><p>建议优先修改为草稿后发布。删除会影响现有商城，订单记录仍保留。</p></AsyncForm></details>}
  </RecordPage>;
  if(view === "import") return <RecordPage title="导入商品资料" onBack={() => open()} description="先检查文件，再确认导入；不会跳过校验直接覆盖资料。"><ProductImport siteId={siteId} products={products} disabled={!canWrite} onDone={catalog => {onProducts(catalog);open();}} /></RecordPage>;
  return <BusinessTable initialQuery={initialFilter} title="商品管理" rows={products} rowKey={p => p.id} searchText={p => `${p.name} ${p.sku} ${p.category}`} status={p => productStatus(p.status)} columns={[{label:"商品",render:p => <><strong>{p.name}</strong><small>{p.category}</small></>},{label:"SKU",render:p=>p.sku},{label:"价格",render:p=>formatMoney(p.price,"USD")},{label:"规格数",render:p=>p.variants.length},{label:"状态",render:p=>productStatus(p.status)}]} actions={<><button type="button" className="button button-outline" onClick={onExport}>导出 CSV</button><button type="button" className="button button-outline" disabled={!canWrite} onClick={()=>open("import")}>导入资料</button><button type="button" className="button button-dark" disabled={!canWrite} onClick={()=>open("new")}>＋ 新增商品</button></>} onOpen={p=>open("edit",p.id)} openLabel={canWrite?"编辑商品":"查看商品"} empty="还没有商品。创建第一件商品后，在这里管理内容和上架状态。" />;
}

function ProductForm({siteId,product,assets,disabled,save}:{siteId:string;product?:PortalProduct;assets:CmsAsset[];disabled:boolean;save:(fields:Record<string,unknown>)=>Promise<void>}) {
  const [uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState("");
  const [images,setImages]=useState(product?.images.join("\n") || "");
  const [variants,setVariants]=useState(product?.variants || []);
  return <div className="bo-card"><AsyncForm disabled={disabled||uploading} label={product?"保存商品修改":"创建商品草稿"} onSave={async form=>{
    const name=String(form.get("name")||"").trim(),price=Number(form.get("price")),sku=String(form.get("sku")||"").trim(),urls=images.split("\n").map(value=>value.trim()).filter(Boolean);
    if(!urls.length)throw new Error("请添加至少一张商品图片。");
    const updated=variants.map(v=>({...v,label:String(form.get(`label-${v.id}`)),optionValues:Object.fromEntries(Object.keys(variantOptionValues(v)).map(key=>[key,String(form.get(`option-${v.id}-${key}`)||"").trim()])),sku:String(form.get(`sku-${v.id}`)),price:form.get(`price-${v.id}`)===""?undefined:Number(form.get(`price-${v.id}`)),available:form.get(`available-${v.id}`)==="on"}));
    await save({...product,name,shortName:name,sku,price,compareAt:form.get("compareAt")===""?undefined:Number(form.get("compareAt")),category:String(form.get("category")),slug:String(form.get("slug")),description:String(form.get("description")),details:String(form.get("details")),status:form.get("status"),image:urls[0],images:urls,alt:String(form.get("alt")||name),...(product?{variants:updated}:{stock:Number(form.get("stock")),colors:["Default"]})});
  }}>
    <h3>商品基础信息</h3><div className="bo-form-grid"><Field label="商品名称 *"><input name="name" required defaultValue={product?.name} maxLength={160}/></Field><Field label="商品访问路径 *" help="小写英文、数字和连字符，如 travel-pack。"><input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" defaultValue={product?.slug}/></Field><Field label="商品分类 *"><input name="category" required defaultValue={product?.category}/></Field><Field label="销售状态"><select name="status" defaultValue={product?.status||"draft"}><option value="draft">草稿</option><option value="active">上架内容（需发布）</option></select></Field></div>
    <Field label="简短介绍 *"><textarea name="description" required defaultValue={product?.description}/></Field><Field label="商品详情与材质 *"><textarea name="details" required defaultValue={product?.details}/></Field>
    <h3>图片与展示</h3><Field label={uploading?"正在上传图片…":"上传商品图片（不超过 10MB）"}><input type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif" onChange={async event=>{const file=event.target.files?.[0];if(!file)return;event.target.value="";setUploading(true);setUploadError("");try{const form=new FormData();form.set("siteId",siteId);form.set("file",file);const result=await workspaceRequest<{asset:CmsAsset}>("/api/merchant/assets",{method:"POST",body:form});setImages(current=>[current,result.asset.url].filter(Boolean).join("\n"));}catch(cause){setUploadError(cause instanceof Error?cause.message:"图片上传失败");}finally{setUploading(false);}}}/></Field>{uploadError&&<div className="bo-error" role="alert">{uploadError}</div>}<Field label="商品图片地址 *" help="每行一个图片地址；第一张作为主图。"><textarea value={images} onChange={event=>setImages(event.target.value)} required/></Field><Field label="选择已有媒体"><select value="" onChange={event=>{if(event.target.value)setImages(current=>[current,event.target.value].filter(Boolean).join("\n"));}}><option value="">从店铺媒体库添加图片</option>{assets.map(asset=><option key={asset.id} value={asset.url}>{asset.assetKey}</option>)}</select></Field><Field label="图片描述"><input name="alt" defaultValue={product?.alt}/></Field>
    <h3>价格与规格</h3><div className="bo-form-grid"><Field label="商品 SKU *"><input name="sku" required defaultValue={product?.sku}/></Field><Field label="销售价（USD） *"><input name="price" type="number" min="0.01" step="0.01" required defaultValue={product?.price}/></Field><Field label="划线价（USD）"><input name="compareAt" type="number" min="0" step="0.01" defaultValue={product?.compareAt}/></Field>{!product&&<Field label="初始库存"><input name="stock" type="number" min="0" max="1000000" step="1" defaultValue="0" required/></Field>}</div>
    {product&&<><div className="bo-info">实时库存不在商品编辑页修改；各规格保留原有库存字段。</div>{variants.map(v=><section className="bo-card" key={v.id}><h3>{v.label}</h3><div className="bo-form-grid">{Object.entries(variantOptionValues(v)).map(([key,value])=><Field key={key} label={key+" 选项值"}><input name={`option-${v.id}-${key}`} defaultValue={value} required/></Field>)}<Field label="规格名称"><input name={`label-${v.id}`} required defaultValue={v.label}/></Field><Field label="规格 SKU"><input name={`sku-${v.id}`} required defaultValue={v.sku}/></Field><Field label="规格价格（留空使用商品价）"><input name={`price-${v.id}`} type="number" min="0.01" step="0.01" defaultValue={v.price}/></Field><Field label="是否可售"><input name={`available-${v.id}`} type="checkbox" defaultChecked={v.available}/></Field></div></section>)}<button type="button" className="button button-outline" onClick={()=>setVariants(current=>[...current,{id:crypto.randomUUID(),label:"新规格",sku:"",swatch:"#aab4c2",optionType:"Option",available:true,stock:0}])}>添加规格</button></>}
  </AsyncForm></div>;
}

function ProductImport({siteId,products,disabled,onDone}:{siteId:string;products:PortalProduct[];disabled:boolean;onDone:(products:PortalProduct[])=>void}){
  return <div className="bo-card"><AsyncForm label="校验并确认导入" disabled={disabled} onSave={async form=>{
    const file=form.get("file");if(!(file instanceof File)||!file.size)throw new Error("请选择 CSV 或 JSON 文件。");if(file.size>5*1024*1024)throw new Error("文件不能超过 5MB。");
    const content=await file.text();let fields:Record<string,unknown>;
    if(file.name.toLowerCase().endsWith(".json")){const parsed:unknown=JSON.parse(content);if(!Array.isArray(parsed))throw new Error("JSON 顶层必须是商品数组。");const merged=[...products];for(const value of parsed){if(!value||typeof value!=="object"||!("id"in value)||typeof value.id!=="string")throw new Error("JSON 每条商品必须包含 id，请先导出现有资料参考结构。");const at=merged.findIndex(p=>p.id===value.id);if(at>=0)merged[at]={...merged[at],...value};else merged.push(value as PortalProduct);}fields={products:merged};}else fields={productCsv:content};
    const preview=await merchantWrite<{valid:boolean;errors:string[];warnings:string[]}>(siteId,"catalog","POST",{...fields,dryRun:true});if(!preview.valid)throw new Error(preview.errors.join("；"));
    if(!window.confirm(`文件校验通过。确认把资料写入当前店铺草稿？${preview.warnings?.length?"\n"+preview.warnings.join("\n"):""}`))return;
    const result=await merchantWrite<{catalog:PortalProduct[]}>(siteId,"catalog","POST",fields);onDone(result.catalog);
  }}><Field label="商品 CSV / JSON 文件 *"><input name="file" type="file" accept=".csv,.json" required/></Field><p className="bo-info">CSV 按商品标识合并；JSON 在导入前与当前目录合并，保留未涉及的商品。接口会保存导入前版本记录。</p></AsyncForm></div>;
}

export function MerchantInventory({siteId,rows,canWrite,onRows}:{siteId:string;rows:InventoryRow[];canWrite:boolean;onRows:(rows:InventoryRow[])=>void}){
  const {view,record,open}=useBusinessView(siteId+":inventory");const selected=rows.find(row=>`${row.productId}:${row.variantId}`===record);
  if(view)return <RecordPage title="调整商品库存" onBack={()=>open()}>{!selected?<div className="bo-empty">库存记录不存在，请返回刷新。</div>:<div className="bo-card"><h3>{selected.productName} · {selected.variantLabel}</h3><p>SKU：{selected.sku} · 总库存 {selected.quantity} · 已锁定 {selected.reservedQuantity} · 可售 {selected.quantity-selected.reservedQuantity}</p><AsyncForm disabled={!canWrite} label="确认库存调整" onSave={async form=>{const delta=Number(form.get("delta"));if(!Number.isInteger(delta)||!delta)throw new Error("请输入非零整数，补货为正数、盘亏为负数。");const quantity=selected.quantity+delta;if(quantity<selected.reservedQuantity)throw new Error("不能扣减已锁定库存。");const result=await merchantWrite<{inventory:InventoryRow}>(siteId,"inventory","PATCH",{productId:selected.productId,variantId:selected.variantId,quantity});onRows(rows.map(row=>row.productId===selected.productId&&row.variantId===selected.variantId?{...row,...result.inventory}:row));open();}}><Field label="本次增减数量 *"><input name="delta" type="number" step="1" required/></Field><p className="bo-info">保存后影响实时可售库存。系统会保留库存调整记录，不会修改其他规格。</p></AsyncForm></div>}</RecordPage>;
  return <BusinessTable title="库存管理" rows={rows} rowKey={r=>`${r.productId}:${r.variantId}`} searchText={r=>`${r.productName} ${r.variantLabel} ${r.sku}`} status={r=>r.quantity-r.reservedQuantity<=0?"缺货":r.quantity-r.reservedQuantity<=5?"低库存":"正常"} columns={[{label:"商品 / 规格",render:r=><><strong>{r.productName}</strong><small>{r.variantLabel}</small></>},{label:"SKU",render:r=>r.sku},{label:"可售",render:r=>r.quantity-r.reservedQuantity},{label:"锁定",render:r=>r.reservedQuantity},{label:"总量",render:r=>r.quantity}]} onOpen={r=>open("adjust",`${r.productId}:${r.variantId}`)} openLabel={canWrite?"调整库存":"查看库存"} empty="商品发布后初始化实时库存。请先发布商品，再进行补货或盘点。"/>;
}
