"use client";
import { useEffect, useRef, useState } from "react";
import type { AfterSales, MerchantTeamMember, PortalOrder, ClientOrderDetail } from "../client/client-portal";
import { AsyncForm, BusinessField as Field, BusinessTable, RecordPage, useBusinessView } from "../components/backoffice";
import { formatMoney } from "../lib/format-money";
import { fulfillmentLabel, memberRoleLabel, merchantWrite, paymentLabel, workspaceRequest } from "./workspace-api";

export function MerchantTeam({siteId,members,canWrite,onMembers}:{siteId:string;members:MerchantTeamMember[];canWrite:boolean;onMembers:(members:MerchantTeamMember[])=>void}){
  const {view,record,open}=useBusinessView(siteId+":team");const member=members.find(m=>m.userId===record);
  if(view)return <RecordPage title={view==="new"?"添加店铺成员":"管理店铺成员权限"} onBack={()=>open()} aside={<div className="bo-info">店铺管理员负责商品与营销；履约人员负责订单和发货；售后客服只能查看订单并处理售后。这里不会授予平台后台权限。</div>}>
    {view!=="new"&&!member?<div className="bo-empty">成员不存在。</div>:<div className="bo-card"><AsyncForm key={record||"new"} disabled={!canWrite||member?.role==="merchant_owner"} onSave={async form=>{const result=await merchantWrite<{member:MerchantTeamMember}>(siteId,"team",member?"PATCH":"POST",{email:String(form.get("email")),role:form.get("role"),...(member?{userId:member.userId}:{})});onMembers([...members.filter(m=>m.userId!==result.member.userId),result.member]);open();}}><Field label="成员邮箱 *"><input name="email" type="email" required defaultValue={member?.email} readOnly={!!member}/></Field><Field label="店铺岗位"><select name="role" defaultValue={member?.role||"merchant_staff"}><option value="merchant_manager">店铺管理员</option><option value="merchant_staff">订单与履约人员</option><option value="merchant_support">售后客服</option>{member?.role==="merchant_owner"&&<option value="merchant_owner">店铺所有者</option>}</select></Field>{member?.role==="merchant_owner"&&<p className="bo-info">店铺所有者在本页面保持保护，不直接降级或删除。</p>}</AsyncForm>{member&&member.role!=="merchant_owner"&&canWrite&&<AsyncForm label="移除此成员" onSave={async()=>{if(!window.confirm(`移除 ${member.email} 的店铺访问权限？`))return;const result=await merchantWrite<{members:MerchantTeamMember[]}>(siteId,"team","DELETE",{userId:member.userId});onMembers(result.members);open();}}><p>移除后不能再访问当前店铺，其他店铺权限不受影响。</p></AsyncForm>}</div>}
  </RecordPage>;
  return <BusinessTable title="店铺成员" rows={members} rowKey={m=>m.userId} searchText={m=>`${m.email} ${memberRoleLabel(m.role)}`} columns={[{label:"邮箱",render:m=>m.email},{label:"岗位",render:m=>memberRoleLabel(m.role)},{label:"加入时间",render:m=>new Date(m.createdAt).toLocaleDateString()}]} onOpen={m=>open("edit",m.userId)} openLabel="管理权限" actions={<button type="button" className="button button-dark" disabled={!canWrite} onClick={()=>open("new")}>＋ 添加成员</button>}/>;
}

const caseLabels:Record<string,string>={submitted:"待处理",processing:"处理中",approved:"已同意",rejected:"已拒绝",completed:"已结案"};
export function MerchantAfterSales({siteId,requests,canWrite,onRequests}:{siteId:string;requests:AfterSales[];canWrite:boolean;onRequests:(requests:AfterSales[])=>void}){
  const {view,record,open}=useBusinessView(siteId+":after-sales");const selected=requests.find(r=>r.id===record);
  if(view)return <RecordPage title={view==="new"?"登记售后申请":"处理售后申请"} onBack={()=>open()} description="售后结案和实际退款是两个操作；退款结果以订单支付记录为准。"><div className="bo-card">{view!=="new"&&!selected?<div className="bo-empty">售后记录不存在。</div>:<AsyncForm key={record||"new"} disabled={!canWrite} label={selected?"保存处理结果":"登记售后"} onSave={async form=>{let fields:Record<string,unknown>;if(selected){if(form.get("status")==="completed"&&!String(form.get("adminNote")||"").trim())throw new Error("结案前请填写处理结论。");fields={id:selected.id,status:form.get("status"),adminNote:form.get("adminNote")};}else fields={...Object.fromEntries(form),requestedAmount:form.get("requestedAmount")?Number(form.get("requestedAmount")):undefined};const result=await merchantWrite<{request:AfterSales}>(siteId,"after-sales",selected?"PATCH":"POST",fields);onRequests([result.request,...requests.filter(r=>r.id!==result.request.id)]);open();}}>
    {selected?<><dl className="bo-facts"><div><dt>订单</dt><dd>{selected.orderNumber||selected.orderId}</dd></div><div><dt>客户邮箱</dt><dd>{selected.email}</dd></div><div><dt>申请原因</dt><dd>{selected.reason}</dd></div><div><dt>客户补充</dt><dd>{selected.customerNote||"无"}</dd></div></dl><Field label="处理状态"><select name="status" defaultValue={selected.status}>{Object.entries(caseLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></Field><Field label="内部处理结论"><textarea name="adminNote" defaultValue={selected.adminNote||""}/></Field></>:<><div className="bo-form-grid"><Field label="订单号 *"><input name="orderNumber" required/></Field><Field label="下单邮箱 *"><input name="email" type="email" required/></Field><Field label="申请类型"><select name="requestType"><option value="return">退货</option><option value="refund">退款</option><option value="exchange">换货</option></select></Field><Field label="申请金额（可选）"><input name="requestedAmount" type="number" min="0.01" step="0.01"/></Field></div><Field label="申请原因 *"><textarea name="reason" required/></Field><Field label="客户补充说明"><textarea name="customerNote"/></Field></>}
  </AsyncForm>}</div></RecordPage>;
  return <BusinessTable title="售后处理" rows={requests} rowKey={r=>r.id} searchText={r=>`${r.orderNumber} ${r.email} ${r.reason}`} status={r=>caseLabels[r.status]||r.status} columns={[{label:"订单",render:r=>r.orderNumber||r.orderId},{label:"客户邮箱",render:r=>r.email},{label:"原因",render:r=>r.reason},{label:"状态",render:r=>caseLabels[r.status]||r.status}]} onOpen={r=>open("detail",r.id)} openLabel="处理申请" actions={<button type="button" className="button button-dark" disabled={!canWrite} onClick={()=>open("new")}>＋ 登记售后</button>}/>;
}

export function MerchantOrders({siteId,orders,canWrite,canRefund,onUpdated,initialFilter=""}:{initialFilter?:string;siteId:string;orders:PortalOrder[];canWrite:boolean;canRefund:boolean;onUpdated:()=>Promise<void>}){
  const {view,record,open}=useBusinessView(siteId+":orders");
  if(view)return <RecordPage title="订单详情" onBack={()=>open()}><OrderRecord key={`${siteId}:${record}`} siteId={siteId} orderId={record} canWrite={canWrite} canRefund={canRefund} onUpdated={onUpdated}/></RecordPage>;
  return <BusinessTable initialQuery={initialFilter} title="订单管理" rows={orders} rowKey={o=>o.id} searchText={o=>`${o.orderNumber} ${o.customerName} ${o.email} ${o.trackingNumber}`} status={o=>fulfillmentLabel(o.fulfillmentStatus)} columns={[{label:"订单号",render:o=>o.orderNumber},{label:"客户",render:o=><>{o.customerName}<small>{o.email}</small></>},{label:"实付",render:o=>formatMoney(o.total,o.currency)},{label:"支付",render:o=>paymentLabel(o.paymentStatus)},{label:"配送",render:o=>fulfillmentLabel(o.fulfillmentStatus)},{label:"创建时间",render:o=>new Date(o.createdAt).toLocaleString()}]} onOpen={o=>open("detail",o.id)} empty="此店铺还没有订单。"/>;
}

function OrderRecord({siteId,orderId,canWrite,canRefund,onUpdated}:{siteId:string;orderId:string;canWrite:boolean;canRefund:boolean;onUpdated:()=>Promise<void>}){
  const [detail,setDetail]=useState<ClientOrderDetail|null>(null);const [error,setError]=useState("");const [nonce,setNonce]=useState(0);const [task,setTask]=useState("summary");
  const refundRequestKey=useRef(crypto.randomUUID());
  useEffect(()=>{const controller=new AbortController();void workspaceRequest<ClientOrderDetail>(`/api/merchant/orders?siteId=${encodeURIComponent(siteId)}&orderId=${encodeURIComponent(orderId)}`,{signal:controller.signal}).then(setDetail).catch(cause=>{if(!controller.signal.aborted)setError(cause.message);});return()=>controller.abort();},[siteId,orderId,nonce]);
  async function refresh(){setTask("summary");setNonce(n=>n+1);await onUpdated().catch(()=>setError("操作已保存，但列表刷新失败，请重新打开订单核对。"));}
  if(error)return <div className="bo-error" role="alert">{error}<button type="button" className="text-button" onClick={()=>{setError("");setNonce(n=>n+1);}}>重新读取</button></div>;
  if(!detail)return <div className="bo-card" role="status">正在读取当前订单…</div>;
  const o=detail.order;const pending=detail.refunds.filter(r=>["pending","processing"].includes(r.status)).reduce((sum,r)=>sum+r.amount,0);const remaining=Math.max(0,o.total-o.refundTotal-pending);
  const next:Record<string,string[]>={unfulfilled:["processing","cancelled"],processing:["shipped","cancelled"],shipped:["delivered"],delivered:[],cancelled:[]};
  return <><div className="bo-card"><div className="bo-card-heading"><h2>{o.orderNumber}</h2><div className="bo-actions"><button type="button" className="button button-outline" disabled={!canWrite||!next[o.fulfillmentStatus]?.length} onClick={()=>setTask("shipping")}>处理配送</button><button type="button" className="button button-outline" disabled={!canRefund||remaining<=0||pending>0||!["paid","partially_refunded"].includes(o.paymentStatus)} onClick={()=>setTask("refund")}>申请退款</button></div></div><dl className="bo-facts">{[["支付状态",paymentLabel(o.paymentStatus)],["配送状态",fulfillmentLabel(o.fulfillmentStatus)],["实付金额",formatMoney(o.total,o.currency)],["累计已退款",formatMoney(o.refundTotal,o.currency)],["客户",`${o.customerName} · ${o.email}`],["收货地址",Object.values(o.shippingAddress).filter(Boolean).join(", ")],["物流单号",o.trackingNumber||"尚未填写"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div>
    {task==="shipping"&&<div className="bo-card"><h3>更新配送状态</h3><AsyncForm disabled={!canWrite} label="确认配送更新" onSave={async form=>{const status=String(form.get("fulfillmentStatus"));if(status==="shipped"&&!String(form.get("trackingNumber")||"").trim())throw new Error("发货前请填写物流单号。");if(!window.confirm(`将订单更新为“${fulfillmentLabel(status)}”？`))return;await merchantWrite(siteId,"orders","PATCH",{orderId,fulfillmentStatus:status,trackingNumber:form.get("trackingNumber")});await refresh();}}><Field label="下一步配送状态"><select name="fulfillmentStatus">{(next[o.fulfillmentStatus]||[]).map(value=><option key={value} value={value}>{fulfillmentLabel(value)}</option>)}</select></Field><Field label="物流单号"><input name="trackingNumber" defaultValue={o.trackingNumber||""}/></Field><p className="bo-info">配送更新只改变履约状态，不会把未付款订单标为付款成功。</p></AsyncForm></div>}
    {task==="refund"&&<div className="bo-card"><h3>PayPal 退款</h3><AsyncForm disabled={!canRefund} label="确认提交 PayPal 退款" onSave={async form=>{const amount=Number(form.get("amount"));if(Math.round(amount*100)>Math.round(remaining*100)||amount<=0)throw new Error("退款金额超出当前可退余额。");if(!window.confirm(`确认向客户退还 ${formatMoney(amount,o.currency)}？实际结果以 PayPal 回执为准。`))return;await merchantWrite(siteId,"refunds","POST",{orderId,amount,reason:form.get("reason"),idempotencyKey:refundRequestKey.current});refundRequestKey.current=crypto.randomUUID();await refresh();}}><Field label={`退款金额（${o.currency.toUpperCase()}） *`}><input name="amount" type="number" min="0.01" max={remaining.toFixed(2)} step="0.01" required defaultValue={remaining.toFixed(2)}/></Field><Field label="退款原因 *"><textarea name="reason" required/></Field><p className="bo-info">退款提交后可能仍在处理中。每次提交均使用唯一请求号，网络超时不会在 PayPal 重复退款；退货验收后再通过库存管理回补库存。</p></AsyncForm></div>}
    <BusinessTable title="订单商品" rows={detail.items} rowKey={item=>item.id} searchText={item=>`${item.name} ${item.sku}`} columns={[{label:"商品",render:item=>item.name},{label:"规格",render:item=>item.variantLabel},{label:"SKU",render:item=>item.sku},{label:"数量",render:item=>item.quantity},{label:"单价",render:item=>formatMoney(item.unitPrice,o.currency)}]}/>
    <div className="bo-card"><h3>内部备注</h3><AsyncForm key={o.id+String(o.adminNote)} disabled={!canWrite} label="保存内部备注" onSave={async form=>{await merchantWrite(siteId,"orders","PATCH",{orderId,adminNote:form.get("adminNote")});await refresh();}}><Field label="订单备注（不发给客户）"><textarea name="adminNote" defaultValue={o.adminNote||""}/></Field></AsyncForm></div>
    <BusinessTable title="退款记录" rows={detail.refunds} rowKey={r=>r.id} searchText={r=>`${r.reason} ${r.status}`} columns={[{label:"金额",render:r=>formatMoney(r.amount,r.currency)},{label:"状态",render:r=>r.status},{label:"原因",render:r=>r.reason||"—"},{label:"处理信息",render:r=>r.error||"以支付方回执为准"}]}/>
    <BusinessTable title="状态记录" rows={detail.stateEvents} rowKey={r=>r.id} searchText={r=>`${r.toStatus} ${r.reason}`} columns={[{label:"时间",render:r=>new Date(r.createdAt).toLocaleString()},{label:"状态",render:r=>fulfillmentLabel(r.toStatus)},{label:"说明",render:r=>r.reason||"—"}]}/>
  </>;
}
