"use client";

import Link from "./components/site-link";
import { NewsletterForm } from "./components/newsletter-form";
import { ProductCard } from "./components/product-card";
import { useSiteRuntime } from "./components/site-runtime";

export default function Home() {
  const { config, catalog } = useSiteRuntime();
  const activeProducts = catalog.filter((product) => product.status === "active");
  const brandName = config.brand.name.trim().split(/\s+/)[0];
  const modules = new Set(config.content.home.modules);

  return <>
    {modules.has("hero") && <section className="hero-section"><div className="hero-visual" style={{ backgroundImage: `url(${config.assets.hero})` }}><div className="hero-overlay" /><div className="container hero-content"><p className="eyebrow eyebrow-light">{config.content.home.heroLabel}</p><h1>{config.content.home.heroTitleLead}<br /><em>{config.content.home.heroTitleAccent}</em></h1><p className="hero-copy">{config.content.home.heroBody}</p><Link href="/shop" className="button button-light">{config.content.home.heroCta} <span>-&gt;</span></Link></div><div className="hero-caption">01 / 04 - The art of getting there</div></div></section>}
    {modules.has("intro") && <section className="intro-section container section-pad"><div className="section-kicker"><span>01</span><span>{config.content.home.introLabel}</span></div><div className="intro-grid"><h2>{config.content.home.introTitleLead}<br /><em>{config.content.home.introTitleAccent}</em></h2><div><p className="lead">{config.content.home.introBody}</p><Link href="/about" className="text-link">Read our story <span>-&gt;</span></Link></div></div></section>}
    {modules.has("products") && <section className="product-section section-pad"><div className="container"><div className="section-heading"><div><p className="eyebrow">{config.content.home.productsLabel}</p><h2>{config.content.home.productsTitleLead}<br /><em>{config.content.home.productsTitleAccent}</em></h2></div><Link href="/shop" className="text-link">Shop all gear <span>-&gt;</span></Link></div><div className="product-grid home-product-grid">{activeProducts.filter((product) => product.featured).slice(0, 3).map((product) => <ProductCard key={product.id} product={product} />)}</div></div></section>}
    {modules.has("story") && <section className="split-story container section-pad"><div className="story-image"><img src={config.assets.story} alt="Mist moving through a mountain valley" /></div><div className="story-copy"><p className="eyebrow">{config.content.home.storyLabel}</p><h2>{config.content.home.storyTitleLead}<br /><em>{config.content.home.storyTitleAccent}</em></h2><p>{config.content.home.storyBody}</p><Link href="/about" className="button button-outline">Why {brandName} <span>-&gt;</span></Link></div></section>}
    {modules.has("journal") && <section className="journal-section section-pad"><div className="container"><div className="section-heading"><div><p className="eyebrow">{config.content.home.journalLabel}</p><h2>{config.content.home.journalTitleLead}<br /><em>{config.content.home.journalTitleAccent}</em></h2></div><Link href="/faq" className="text-link">More notes <span>-&gt;</span></Link></div><div className="journal-grid"><Link href="/shipping" className="journal-card journal-card-large"><img src={config.assets.journalHero} alt="Hiker looking across a mountain landscape" /><div><span>Field notes / 06.12.24</span><h3>How to pack for the version of a trip you can&apos;t predict.</h3><span className="text-link">Read article -&gt;</span></div></Link><div className="journal-list"><Link href="/faq" className="journal-small"><span>01</span><div><span>Good questions</span><h3>What makes a piece worth carrying?</h3></div><span>-&gt;</span></Link><Link href="/shipping" className="journal-small"><span>02</span><div><span>On the way</span><h3>Our approach to less wasteful shipping.</h3></div><span>-&gt;</span></Link><Link href="/about" className="journal-small"><span>03</span><div><span>From the archive</span><h3>A field guide to the {config.brand.name} color palette.</h3></div><span>-&gt;</span></Link></div></div></div></section>}
    {modules.has("newsletter") && <section className="newsletter-section"><div className="container newsletter-inner"><p className="eyebrow eyebrow-light">{config.content.home.newsletterLabel}</p><h2>{config.content.home.newsletterTitleLead}<br /><em>{config.content.home.newsletterTitleAccent}</em></h2><p>{config.content.home.newsletterBody}</p><NewsletterForm /><small>By subscribing, you agree to our terms. No noise, ever.</small></div></section>}
  </>;
}
