"use client";

import Link from "next/link";
import { useState } from "react";
import { useStore } from "../components/cart-store";

export default function CheckoutPage() {
  const { cart, subtotal, hydrated } = useStore();
  const [submitted, setSubmitted] = useState(false);
  if (!hydrated) return <div className="loading-state container section-pad">Loading secure checkout…</div>;
  if (submitted) return <div className="empty-state container section-pad"><span className="empty-mark">✓</span><p className="eyebrow">Order received</p><h1>See you out there.</h1><p>Your demo order is in. We’ll use this space for confirmation details when payments are connected.</p><Link href="/shop" className="button button-dark">Continue shopping <span>↗</span></Link></div>;
  if (!cart.length) return <div className="empty-state container section-pad"><span className="empty-mark">◌</span><h1>Your bag is empty.</h1><p>Add something before you check out.</p><Link href="/shop" className="button button-dark">Browse gear <span>↗</span></Link></div>;
  return <div className="checkout-page container section-pad"><div className="breadcrumbs"><Link href="/cart">Bag</Link><span>/</span><span>Checkout</span></div><div className="checkout-layout"><form className="checkout-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><div className="checkout-heading"><p className="eyebrow">Northline / Checkout</p><h1>Let’s get you<br /><em>on your way.</em></h1><p>This is a demo checkout. No payment will be processed.</p></div><fieldset><legend>Contact</legend><label>Email address<input type="email" required placeholder="you@example.com" /></label><label className="checkbox-label"><input type="checkbox" /> Email me with field notes and new gear</label></fieldset><fieldset><legend>Delivery</legend><div className="form-two"><label>First name<input required placeholder="First name" /></label><label>Last name<input required placeholder="Last name" /></label></div><label>Address<input required placeholder="Street address" /></label><div className="form-three"><label>City<input required placeholder="City" /></label><label>State / region<input required placeholder="State" /></label><label>ZIP code<input required placeholder="ZIP" /></label></div><label>Country<select defaultValue="United States"><option>United States</option><option>Canada</option><option>United Kingdom</option><option>Australia</option></select></label></fieldset><fieldset><legend>Payment</legend><div className="payment-placeholder"><span>Demo mode</span><p>Payment processing will be connected here.</p></div></fieldset><button className="button button-dark button-wide" type="submit">Place demo order <span>↗</span></button></form><aside className="checkout-summary"><p className="eyebrow">Your order</p>{cart.map((item) => <div className="checkout-line" key={item.id}><img src={item.image} alt="" /><div><strong>{item.name}</strong><span>Qty {item.quantity}</span></div><strong>${item.price * item.quantity}</strong></div>)}<div className="summary-total"><span>Total</span><strong>${subtotal}</strong></div><p className="secure-note">Free US shipping on orders over $100.</p></aside></div></div>;
}
