"use client";

import { useEffect, useState } from "react";
import { formatMoney } from "../../../lib/format-money";
import { trackingUrl } from "../../../lib/tracking";
import { ReorderButton } from "../../../components/reorder-button";

type Detail = { order: { orderNumber: string; email: string; customerName: string; total: number; currency: string; paymentStatus: string; fulfillmentStatus: string; trackingNumber: string | null; createdAt: string; shippingAddress: Record<string, string>; refundTotal: number }; items: Array<{ id: string; name: string; variantLabel: string; quantity: number; unitPrice: number }>; stateEvents: Array<{ id: string; toStatus: string; reason: string | null; createdAt: string }>; refunds: Array<{ id: string; amount: number; currency: string; status: string; reason: string | null; createdAt: string }> };

export default function AccountOrderPage({ params }: { params: Promise<{ orderId: string }> }) {
  const [orderId, setOrderId] = useState("");
  const [detail, setDetail] = useState<Detail | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void params.then(({ orderId: nextOrderId }) => { setOrderId(nextOrderId); void fetch(`/api/account/orders?orderId=${encodeURIComponent(nextOrderId)}`, { cache: "no-store" }).then(async (response) => { const payload = await response.json().catch(() => ({})) as { order?: Detail; error?: string }; if (!response.ok || !payload.order) throw new Error(payload.error || "Order unavailable."); setDetail(payload.order); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Order unavailable.")); }); }, [params]);
  if (error) return <main className="account-shell container"><section className="account-empty"><p className="eyebrow">Order support</p><h1>That order is unavailable.</h1><p>{error}</p><a className="button button-outline" href="/account">Back to account <span>→</span></a></section></main>;
  if (!detail) return <main className="account-shell container"><section className="account-loading"><p className="eyebrow">Order {orderId}</p><h1>Loading order details.</h1></section></main>;
  const address = Object.values(detail.order.shippingAddress || {}).filter(Boolean).join(", ");
  const carrierLink = trackingUrl(detail.order.trackingNumber);
  return <main className="account-shell container"><div className="account-back"><a className="text-link" href="/account">← Back to account</a></div><header className="account-header"><div><p className="eyebrow">Order {detail.order.orderNumber}</p><h1>On its way<br /><em>to you.</em></h1></div><span className="account-order-status">{detail.order.paymentStatus} · {detail.order.fulfillmentStatus}</span></header><section className="account-order-detail-grid"><article className="account-panel"><p className="eyebrow">Items</p>{detail.items.map((item) => <div className="account-detail-item" key={item.id}><span><strong>{item.name}</strong><small>{item.variantLabel} × {item.quantity}</small></span><strong>{formatMoney(item.unitPrice * item.quantity, detail.order.currency)}</strong></div>)}<p className="account-detail-total">Total <strong>{formatMoney(detail.order.total, detail.order.currency)}</strong></p></article><article className="account-panel"><p className="eyebrow">Delivery</p><h2>{detail.order.trackingNumber ? "Tracking is active." : "Preparing your order."}</h2>{detail.order.trackingNumber && (carrierLink ? <p><a className="text-link" href={carrierLink} target="_blank" rel="noreferrer">Track {detail.order.trackingNumber} ↗</a></p> : <p>Tracking number: {detail.order.trackingNumber}</p>)}{!detail.order.trackingNumber && <p>We will add a tracking number as soon as the order ships.</p>}<p className="account-detail-address">{address}</p><ReorderButton orderId={orderId} /></article></section><section className="account-panel account-timeline"><p className="eyebrow">Order timeline</p>{detail.stateEvents.map((event) => <div key={event.id}><span>{event.toStatus}</span><small>{new Date(event.createdAt).toLocaleString()} · {event.reason || "Status updated"}</small></div>)}{!detail.stateEvents.length && <p className="account-note">Payment and fulfillment updates will appear here.</p>}{detail.refunds.length > 0 && <div className="account-refund-note">Refunded {formatMoney(detail.order.refundTotal, detail.order.currency)} across {detail.refunds.length} record(s).</div>}</section></main>;
}
