"use client";

import Link from "next/link";
import { ProductCard } from "../components/product-card";
import { useSiteRuntime } from "../components/site-runtime";

export function StorefrontPreview() {
  const { config, catalog, cmsStatus } = useSiteRuntime();
  const activeCatalog = catalog.filter((product) => product.status === "active");
  const brandParts = config.brand.name.trim().split(/\s+/);
  return <div className="preview-page"><div className="preview-bar"><span>CLIENT PREVIEW / {cmsStatus === "synced" || cmsStatus === "saved" ? "CMS DATA" : "LOCAL FALLBACK"}</span><div><Link href="/admin">Back to studio</Link><Link href="/shop">Open storefront</Link></div></div><section className="preview-hero" style={{ backgroundImage: `url(${config.assets.hero})` }}><div className="hero-overlay" /><div className="container preview-hero-content"><p className="eyebrow eyebrow-light">{config.content.home.heroLabel}</p><div className="preview-wordmark"><span className="wordmark-mark">{config.brand.mark}</span><span>{brandParts[0]} <em>{brandParts.slice(1).join(" ")}</em></span></div><h1>{config.content.home.heroTitleLead}<br /><em>{config.content.home.heroTitleAccent}</em></h1><p>{config.content.home.heroBody}</p><Link href="/shop" className="button button-light">{config.content.home.heroCta} -&gt;</Link></div></section><section className="container section-pad preview-copy"><p className="eyebrow">{config.brand.name} / Client handoff preview</p><h2>{config.brand.tagline}</h2><p>{config.brand.descriptor}</p></section><section className="preview-products"><div className="container section-pad"><div className="section-heading"><div><p className="eyebrow">Featured catalog</p><h2>Ready to<br /><em>go live.</em></h2></div><Link href="/admin?tab=catalog" className="text-link">Edit products -&gt;</Link></div>{activeCatalog.length ? <div className="product-grid">{activeCatalog.filter((product) => product.featured).slice(0, 3).map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="empty-state"><h2>No published products.</h2><p>Return to the studio and publish at least one product.</p></div>}</div></section><section className="preview-footer"><div className="container"><div className="preview-wordmark"><span className="wordmark-mark">{config.brand.mark}</span><span>{brandParts[0]} <em>{brandParts.slice(1).join(" ")}</em></span></div><p>{config.brand.footerLine}</p><a href={`mailto:${config.content.contact.email}`}>{config.content.contact.email}</a></div></section></div>;
}
